#Phantom_1
/gate/world/daughters/name plasticPhantom
/gate/world/daughters/insert cylinder
/gate/plasticPhantom/setMaterial Air
#/gate/plasticPhantom/vis/setColor blue
#/gate/plasticPhantom/vis/setVisible True
/gate/plasticPhantom/geometry/setRmin 0 mm
/gate/plasticPhantom/geometry/setRmax 31.5 mm
/gate/plasticPhantom/geometry/setHeight 1000 mm
/gate/plasticPhantom/geometry/setPhiStart 0 deg
/gate/plasticPhantom/geometry/setDeltaPhi 360 deg
/gate/plasticPhantom/placement/setTranslation 0 0 0 mm
/gate/plasticPhantom/moves/insert translation
/gate/plasticPhantom/translation/setSpeed 0 0 0 cm/s
/gate/plasticPhantom/moves/insert genericMove
/gate/plasticPhantom/genericMove/setPlacementsFilename Particles11.placement
/control/execute volumesTomove.mac
